import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import client from "../apollo";
import { GET_MENUS } from "../queries/getMenus";

type HomeProps = {
  data: {
    menus: {
      headerMenus: any[];
      footerMenus: any[];
    };
  };
};

const Home: NextPage<HomeProps> = ({ data }) => {
  //console.log(data);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <Layout data={data}>content</Layout> */}
    </>
  );
};
export default Home;

export const getStaticProps: GetStaticProps = async () => {
  const { data, loading, networkStatus } = await client.query({
    query: GET_MENUS,
  });

  //console.log("data", data);
  return {
    props: {
      data: {
        menus: {
          headerMenus: data?.headerMenus?.edges,
          footerMenus: data?.footerMenus?.edges,
        },
      },
    },
  };
};
